"""add lecture_materials

Revision ID: cb64e8bea21e
Revises: 
Create Date: 2026-05-13 01:31:32.187323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cb64e8bea21e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lecture_materials',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('board_no', sa.Integer(), nullable=False),
    sa.Column('subject_code', sa.String(length=100), nullable=False),
    sa.Column('subject_name', sa.String(length=200), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('semester', sa.String(length=1), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('post_title', sa.String(length=300), nullable=False),
    sa.Column('atch_file_id', sa.String(length=100), nullable=False),
    sa.Column('file_sn', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=300), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subject_code', 'atch_file_id', 'file_sn', name='uq_lecture_file')
    )
    op.create_index('ix_lecture_board_no', 'lecture_materials', ['board_no'], unique=False)
    op.create_index('ix_lecture_subject_code', 'lecture_materials', ['subject_code'], unique=False)
    op.alter_column('users', 'student_id',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Unique student ID from KLAS',
               existing_nullable=False)
    op.alter_column('users', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Account approval status: pending, approved, or active',
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('users', 'profile_image',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Base64 encoded profile image from KLAS',
               existing_nullable=True)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='User role: admin or worker',
               existing_nullable=False,
               existing_server_default=sa.text("'worker'::character varying"))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_users_role'), table_name='users')
    op.drop_index(op.f('idx_users_status'), table_name='users')
    op.drop_index(op.f('idx_users_student_id'), table_name='users')
    op.drop_table_comment(
        'users',
        existing_comment='User accounts from KLAS authentication',
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'users',
        'User accounts from KLAS authentication',
        existing_comment=None,
        schema=None
    )
    op.create_index(op.f('idx_users_student_id'), 'users', ['student_id'], unique=False)
    op.create_index(op.f('idx_users_status'), 'users', ['status'], unique=False)
    op.create_index(op.f('idx_users_role'), 'users', ['role'], unique=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=20),
               comment='User role: admin or worker',
               existing_nullable=False,
               existing_server_default=sa.text("'worker'::character varying"))
    op.alter_column('users', 'profile_image',
               existing_type=sa.TEXT(),
               comment='Base64 encoded profile image from KLAS',
               existing_nullable=True)
    op.alter_column('users', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='Account approval status: pending, approved, or active',
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('users', 'student_id',
               existing_type=sa.VARCHAR(length=50),
               comment='Unique student ID from KLAS',
               existing_nullable=False)
    op.drop_index('ix_lecture_subject_code', table_name='lecture_materials')
    op.drop_index('ix_lecture_board_no', table_name='lecture_materials')
    op.drop_table('lecture_materials')
    # ### end Alembic commands ###
