#!/usr/bin/env python3
"""
Generates a daily KLAS note in your Obsidian vault.
Updates: pending homework + unwatched lectures.
Run manually or via cron.
"""

import requests
import json
from datetime import datetime, timezone
from pathlib import Path

# ── Config ────────────────────────────────────────────────────────────────────
STUDENT_ID = "2022203510"
PASSWORD    = "iampro69!"
API_BASE    = "http://localhost:8000/api"
VAULT_DIR   = Path("/Users/universe/Documents/Obsidian Vault/klas")
# ─────────────────────────────────────────────────────────────────────────────


def login() -> str:
    r = requests.post(f"{API_BASE}/auth/login", json={"student_id": STUDENT_ID, "password": PASSWORD})
    r.raise_for_status()
    return r.json()["token"]


def get_pending_hw(token: str) -> list:
    r = requests.get(f"{API_BASE}/homework/all", headers={"Authorization": f"Bearer {token}"})
    r.raise_for_status()
    pending = []
    for course in r.json().get("courses", []):
        for item in course.get("items", []):
            if item.get("submityn") == "N":
                pending.append({
                    "course": course["course_title"],
                    "title": item["title"],
                    "deadline": item.get("expiredate", "?"),
                    "extra_deadline": item.get("reexpiredate"),
                })
    return sorted(pending, key=lambda x: x["deadline"])


def get_unwatched_lectures(token: str) -> list:
    r = requests.get(f"{API_BASE}/recorded-lectures/all", headers={"Authorization": f"Bearer {token}"})
    r.raise_for_status()
    unwatched = []
    for course in r.json().get("courses", []):
        for item in course.get("items", []):
            prog = item.get("prog")
            if prog is not None and prog < 100:
                unwatched.append({
                    "course": course["course_title"],
                    "title": item.get("sbjt", ""),
                    "deadline": item.get("endDate", "?"),
                    "progress": prog,
                    "week": item.get("weekNo", "?"),
                })
    return sorted(unwatched, key=lambda x: x["deadline"])


def build_note(hw: list, lectures: list) -> str:
    today = datetime.now().strftime("%Y-%m-%d")
    lines = [
        f"# KLAS Daily — {today}",
        f"> Updated: {datetime.now().strftime('%Y-%m-%d %H:%M')}",
        "",
    ]

    # Homework
    lines.append("## 📝 Pending Homework")
    if hw:
        for item in hw:
            deadline = item['deadline'].split(' ')[0] if item['deadline'] != '?' else '?'
            extra = f" (extra: {item['extra_deadline'].split(' ')[0]})" if item.get('extra_deadline') else ""
            lines.append(f"- [ ] **{item['title']}** — {item['course']} | due `{deadline}`{extra}")
    else:
        lines.append("- ✅ All homework submitted!")

    lines.append("")

    # Lectures
    lines.append("## 🎬 Unwatched Lectures")
    if lectures:
        for lec in lectures:
            deadline = lec['deadline'].split(' ')[0] if lec['deadline'] != '?' else '?'
            lines.append(f"- [ ] **{lec['title']}** — {lec['course']} | Week {lec['week']} | due `{deadline}` | {lec['progress']}% watched")
    else:
        lines.append("- ✅ All lectures watched!")

    lines.append("")
    lines.append("---")
    lines.append(f"*Generated by [OpenKLAS](http://localhost:8000/docs)*")

    return "\n".join(lines)


def main():
    print("Logging in...")
    token = login()

    print("Fetching homework...")
    hw = get_pending_hw(token)

    print("Fetching lectures...")
    lectures = get_unwatched_lectures(token)

    note = build_note(hw, lectures)

    VAULT_DIR.mkdir(parents=True, exist_ok=True)
    out_path = VAULT_DIR / "KLAS Daily.md"
    out_path.write_text(note, encoding="utf-8")

    print(f"✅ Written to {out_path}")
    print(f"   {len(hw)} pending hw, {len(lectures)} unwatched lectures")


if __name__ == "__main__":
    main()
